### ISSUE TITLE
Session saved every request even if not modified

### ISSUE THREAD

**Issue by alvinchow86** [mbr/flask-kvsession#20]
Supposedly "The session class will save data to the store only when necessary". I noticed that even if the session is not updated on a request, KVSession still write it out (I'm using Redis, and noticed this while monitoring Redis write activity). I noticed this code here (last two lines)

```
class KVSession(CallbackDict, SessionMixin):
...
    def __init__(self, initial=None):
        def _on_update(d):
            d.modified = True

        CallbackDict.__init__(self, initial, _on_update)

        if not initial:
            self.modified = False
```

Right now, if the session already contains any data, `modified` is always True (picking up the default value from SessionMixin). The only case "modified" starts off as True when the KVSession is initialized is for a brand new session.

**Comment by lobeck** [comment]
Hi, i think this is not fixed. I'm using 0.6.1 from pypi

I have a blueprint serving static files on a own subdomain. When doing a curl request without any cookies i'll get a set-cookie header

```
> GET /bower/holderjs/holder.js?version=2.4.1 HTTP/1.1
> User-Agent: curl/7.37.1
> Accept: */*
> Host: static.foobar.dev:8080

* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Length: 23861
< Content-Type: application/javascript
< Last-Modified: Mon, 20 Oct 2014 04:53:48 GMT
< Cache-Control: public, max-age=43200
< Expires: Thu, 05 Feb 2015 11:42:33 GMT
< ETag: "flask-1413780828.0-23861-1336352835"
< Set-Cookie: session=a8a64ad2afc5370b_54d2ae69.Wbu_Tx8L1Evpaa7pLaj1HFrzMS8; Domain=.foobar.dev; HttpOnly; Path=/
< Server: Werkzeug/0.9.6 Python/2.7.9
< Date: Wed, 04 Feb 2015 23:42:33 GMT
```

I also added some debugging with ``pprint(session)``, ``session.modified`` and ``session.new``:

```
modified: True
new: True
<KVSession {'_id': 'f0f59e8a76fee20694f24c84b165703f'}>
```

The route itself just does some input validation and a ``send_file()``, but there is nothing done to the session itself.

Session is initialized by:

```
store = RedisStore(redis.StrictRedis())
KVSessionExtension(store, app)
```

I'll try to take a deeper look in it tomorrow.
