### ISSUE TITLE
SQL Server Schema To Store Session Data

### ISSUE THREAD

**Issue by pournejati** [mbr/flask-kvsession#32]
I want to create a table in my SQL Server to store session data. What would be the schema for that?

**Comment by mbr** [comment]
The schema is usually created by SQLAlchemy. Have a look at the simplekv documentation: http://pythonhosted.org/simplekv/db.html

If you are using SQLAlchemy in your application, just pass the Metadata of your application as the ``metadata`` parameter to the constructor, the necessary tables will be created on it.

If you need raw SQL, have a look at this: http://stackoverflow.com/questions/2128717/sqlalchemy-printing-raw-sql-from-create

You will need to create an empty Metadata object and pass it to the constructor. Afterwards you can print it out.
